# This file contains values from Cookiecutter

default_context:
  project_name: "sys-config"
  project_description: "Awesome `sys-config` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "sys-config"
  license: "GNU GPL v3.0"
  minimal_python_version: 3.9
  github_name: "sys_config"
  email: "hello@sys-config.com"
  version: "0.1.0"
  line_length: "200"
  create_example_template: "none"
