# This file contains values from Cookiecutter

default_context:
  project_name: "sys-config"
  project_description: "Awesome `sys-config` is a Python cli/package created with https://github.com/william-cass-wright/cookiecutter-pypackage-slim"
  organization: "sys-config"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.9
  github_name: "william-cass-wright"
  email: "hello@sys-config.com"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "none"
