name: build

on: [push]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # inputs:
    #   logLevel:
    #     description: 'Log level'
    #     required: true
    #     default: 'warning'
    #   tags:
    #     description: 'Test scenario tags'

jobs:
  build:
    # if: ${{ github.event.label.name == 'build' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    - name: Run tests
      run: |
        make test

    - name: Run safety checks
      run: |
        make check-safety
