# name: Python package
# on:
#   push:
#     tags:
#       - "v*.*.*"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Build and publish to pypi
#         uses: JRubics/poetry-publish@v1.13
#         with:
#           pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
#           repository_name: "sys-config"
#           repository_username: "__token__"
#           repository_url: "https://test.pypi.org/project/sys-config/"
